### ISSUE TITLE
运行报错 

### ISSUE THREAD

**Issue by lampsunny** [babaiwan/YOLOv3-Dishes-identification#2]
ImportError: cannot import name 'multi_gpu_model' from 'tensorflow.keras.utils'
keras版本2.4.3
pyQt5版本5.15.2
tensorflow版本2.4.0

**Comment by babaiwan** [comment]
尝试在python 3.7 环境下运行此程序，或许能解决你的问题？
正常运行会看到缺失log/.h5文件，我晚些时候会上传。
或者你可以自行去下载一个野生的
在根目录创建一个logs文件夹，在文件夹内放置你训练好的.h5权重文件。
依赖情况如下
![image](https://user-images.githubusercontent.com/50008615/103126230-9c066380-46c8-11eb-9f3c-763e0b113aa8.png)

**Comment by lampsunny** [comment]
我现在运行的环境是python3.8
.h5和yolov3.weights都生成了，现在能跑起来，但是识别图像一直报错，实时识别识别不出东西

点识别图像报错

logs/yolo.h5 model, anchors, and classes loaded.
实例化Yolo完成
Traceback (most recent call last):
  File "/System/Volumes/Data/WORK/project/Python/YOLOv3-Dishes-identification-master/MainWindow_2.0.py", line 326, in showPicture
    r_image = self.yolo.detect_image(image)
  File "/System/Volumes/Data/WORK/project/Python/YOLOv3-Dishes-identification-master/yolo.py", line 137, in detect_image
    feed_dict={
  File "/Users/mac/Library/Python/3.8/lib/python/site-packages/tensorflow/python/keras/engine/keras_tensor.py", line 260, in __hash__
    raise TypeError('Tensors are unhashable. (%s)'
TypeError: Tensors are unhashable. (KerasTensor(type_spec=TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='input_1'), name='input_1', description="created by layer 'input_1'"))Instead, use tensor.ref() as the key.
(416, 416, 3)

错误程序在这个位置，不知道怎么调了
yolo.py 第137行

out_boxes, out_scores, out_classes = self.sess.run(
            [self.boxes, self.scores, self.classes],
            feed_dict={
                self.yolo_model.input: image_data,
                self.input_image_shape: [image.size[1], image.size[0]],
                K.learning_phase(): 0
            })

**Comment by sqdhoooo** [comment]
> ImportError：无法从'tensorflow.keras.utils'keras
> 版本2.4.3
> pyQt5版本5.15.2
> tensorflow版本2.4.0导入名称'multi_gpu_model'

我也遇到了这个问题，是怎么解决的啊
cannot import name 'multi_gpu_model' from 'keras.utils' (C:\Users\asus\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\utils\__init__.py)

**Comment by sqdhoooo** [comment]
上面那个问题我解决了，一定要按照yolo的 README文件要求安装tensorflow keras等版本
请问能不能上传一下.h5文件和.weight文件呢。

**Comment by babaiwan** [comment]
我的建议是，你去闲鱼花100多 200 让别人帮你训练一个 h5。或者用开源的免费的h5,外面一抓一大把
这样你既免去了写界面的过程，又有了自己的东西。不是一石二鸟吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月10日(星期三) 下午4:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [babaiwan/YOLOv3-Dishes-identification] 运行报错  (#2)





 
上面那个问题我解决了，一定要按照yolo的 README文件要求安装tensorflow keras等版本
 请问能不能上传一下.h5文件和.weight文件呢。

**Comment by LLL-sudo** [comment]
可以买您的h5参考下吗？

**Comment by babaiwan** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "babaiwan/YOLOv3-Dishes-identification"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月21日(星期天) 晚上8:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [babaiwan/YOLOv3-Dishes-identification] 运行报错  (#2)





 
可以买您的h5参考下吗？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

coco_classes.txt (26B, 2021年03月21日 23:39 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=72653161d0c7cecba470e0f61038031b02550900010850511a500055051505040f011c59010c08190255555007010457040306023628315758065e3e555450474400424f424045340a&code=7e1a6814




voc_classes.txt (26B, 2021年03月21日 23:40 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=2632333387cecdc6f127e2a447310016560a5603050904584f07070a071c060800531e0a535703140457060a5057570f52000156613e324f0d516c500d50414a07411d4719453204&code=b233a129




yolo_anchors.txt (76B, 2021年03月21日 23:40 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=26396364d0c79d9ef02cb2f34238504e055f5402515e07514e0b50530215560053014e5d575e514c535a5601065b0755530c5b5d642862180c550c3b055601090c4b104a104016615e&code=c9cdd8ba




yolo.h5 (237.17M, 2021年04月20日 23:39 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0f623163d6321ac6a077e0f4106505180a010357000306531e07575153480307065b1c010e01031a0703065007015251005b57503662374e5c0e5e4d5e50370a&code=3b1c6e77

**Comment by sqdhoooo** [comment]
Mismatch between model and given anchor and class sizes

**Comment by babaiwan** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "八百万"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月21日(星期天) 晚上11:43
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [babaiwan/YOLOv3-Dishes-identification] 运行报错  (#2)











------------------ 原始邮件 ------------------
发件人:                                                                                                                        "babaiwan/YOLOv3-Dishes-identification"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月21日(星期天) 晚上8:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [babaiwan/YOLOv3-Dishes-identification] 运行报错  (#2)





 
可以买您的h5参考下吗？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.



从QQ邮箱发来的超大附件

coco_classes.txt (26B, 2021年03月23日 23:09 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=2062326285999cc9f677e3f545665119505b54500555025448550557544b570407031f000202061b04030b5452560607575b515b637663550a015d3d000a02451607414c171e173658&code=eb2bcfc6




tiny_yolo_anchors.txt (50B, 2021年03月23日 23:09 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=78313232afc7c79ca124e3a547380a4c0a030a05570a00511f000b0b04150c5a07501f0b075a594e57060a065108590251040756612d38175b5f4b6d1857540c6d505c5109574a101c454a466105&code=2122a88c




voc_classes.txt (26B, 2021年03月23日 23:10 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=70313662decac9cba724e7f51e35041b07035257590d0056190602005d18020101041b0000565419020953015a0600505603035b383a36425b526901545445475142181640413609&code=416b8564




yolo_anchors.txt (77B, 2021年03月23日 23:10 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=76383438d6999e9aa02de5af4366534a02080709505055031e0f070a5d4b5506565a190106545848500d025a00530553025a065c6576611c5c545b670408020d5c4a4716111e15650e&code=3848efae




yolo_weights.h5 (237.17M, 2021年04月22日 23:10 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=73343139d93619c7a421e0ae1f610619035055090c5657501a01555a0e4c000201061c010b51021b0707020a0854060e5201520a396e344f58585e664e045d515f4042175154340b&code=74199a46

**Comment by prejefferson** [comment]
你好，AssertionError: Mismatch between model and given anchor and class sizes出现这个怎么破

**Comment by xiaoxiongmaoywq** [comment]
大佬有空嘛，我这边实在有点不太会做，一直报错，可以加下联系方式私聊嘛，我会给你辛苦费的

**Comment by xiaoxiongmaoywq** [comment]
File "D:\pythontrain\YOLOv3-Dishes-identification-master2\YOLOv3-Dishes-identification-master\yolo.py", line 73, in generate
    self.yolo_model = load_model(model_path, compile=False)
  File "D:\python\anaconda\envs\tf2.0\lib\site-packages\keras\engine\saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "D:\python\anaconda\envs\tf2.0\lib\site-packages\keras\engine\saving.py", line 583, in load_model
    with H5Dict(filepath, mode='r') as h5dict:
  File "D:\python\anaconda\envs\tf2.0\lib\site-packages\keras\utils\io_utils.py", line 191, in __init__
    self.data = h5py.File(path, mode=mode)
  File "D:\python\anaconda\envs\tf2.0\lib\site-packages\h5py\_hl\files.py", line 445, in __init__
    swmr=swmr)
  File "D:\python\anaconda\envs\tf2.0\lib\site-packages\h5py\_hl\files.py", line 195, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 96, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = 'logs/yolo.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
报了很多类似这样的错误，我在网上搜也没搜到相关的结果，很是苦恼

**Comment by xiaoxiongmaoywq** [comment]
[Errno 2] Unable to open file (unable to open file: name = 'logs/yolo.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
这个错，好像是读取失败了

**Comment by fwhrice** [comment]
您好，可以上传您的h5参考下吗？

**Comment by fwhrice** [comment]
> 

您好，数据集也能方便上传一下吗，想学习您的项目，十分感谢

> 您好，可以上传您的h5参考下吗？
